version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - media:/var/lib/postgresql/media
  backend:
    container_name: foodgram-back
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    env_file: .env
    container_name: foodgram-front
    build: ./frontend/
    volumes:
      - ./frontend/:/app/result_build/
      - static:/frontend_static
  nginx:
    container_name: foodgram-proxy
    build: ./infra/
    env_file: .env
    ports:
      - 9090:80
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media
