version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - media:/var/lib/postgresql/media
  backend:
    container_name: foodgram-back
    image: oleinikoves1/foodgram_backend
    env_file: .env
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    env_file: .env
    container_name: foodgram-front
    image: oleinikoves1/foodgram_frontend
    volumes:
      - static:/app/build/
  nginx:
    container_name: foodgram-proxy
    image: oleinikoves1/foodgram_gateway
    env_file: .env
    ports:
      - 9090:80
    volumes:
      - static:/static
      - media:/media