[tool.isort]
profile = "black"
line_length = 79
lines_after_imports = 2
multi_line_output = 0
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
known_first_party = ["recipes", "foodgram", "api"]
known_third_party = ["short_url", "django", "rest_framework", "djoser"]

[tool.flake8]
ignore = ["W503"]
exclude = ["tests/", "*/migrations/", "data/", "venv/", "env/", "docs/", "frontend/", "infra/"]
per-file-ignores = {
    "*/settings.py" = ["E501"],
    "*/manage.py" = ["E501"]
}
max-line-length = 79
