[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 0
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
known_first_party = ["recipes", "foodgram", "api"]

[tool.flake8]
ignore = ["W503"]
exclude = ["tests/", "*/migrations/", "data/", "venv/", "env/", "docs/", "frontend/", "infra/"]
per-file-ignores = {"*/settings.py" = ["E501"]}
max-line-length = 79
